### Used libraries

In [ ]:
import pandas as pd

### Load data from csv datasets

In [4]:
df = pd.read_csv('datasets/job_offer.csv', delimiter= ';')

print(df.shape)
df.head(3)

(5935, 13)

,url,reference,title,detail_entrerpise,mission,profil,market_category,societe,type_contrat,lieu,societe_slug,limite_date,offers_date
0,https://www.portaljob-madagascar.com/emploi/vi...,NaN,electronicien,d'un petit commerce ne il y a plus de cent ans...,L'électronicien industriel est responsable de ...,o solides connaissances en electronique indust...,Ingénierie / industrie / BTP,groupe sipromad,contrat cdi,aucun lieu,groupe sipromad6 electronicien167760,0001-01-01,13/05/2025
1,https://www.portaljob-madagascar.com/emploi/vi...,ENG-C-CPP,c/c++ software engineer,"rejoignez astek madagascar, du groupe astek, p...",Participez à des projets de transformation dig...,- formation bac+3 a bac+5 en informatique\n- m...,Informatique / web,astek madagascar,contrat cdd,aucun lieu,astek madagascar c,0001-01-01,28/09/2024
2,https://www.portaljob-madagascar.com/emploi/vi...,NaN,manager developpement rh,multisectorielle,Rattaché à la Directrice des Ressources Humain...,"• bac +4/5 en gestion, grh, sociologie, droit,...",Management / RH,inviso group,contrat cdi,antananarivo,fly technologies sarl,0001-01-01,14/02/2025

### Remove duplicates in urls and titles

In [5]:
df.drop_duplicates(subset=['url', 'title'])
print(df.shape)
df

(5935, 13)

,url,reference,title,detail_entrerpise,mission,profil,market_category,societe,type_contrat,lieu,societe_slug,limite_date,offers_date
0,https://www.portaljob-madagascar.com/emploi/vi...,NaN,electronicien,d'un petit commerce ne il y a plus de cent ans...,L'électronicien industriel est responsable de ...,o solides connaissances en electronique indust...,Ingénierie / industrie / BTP,groupe sipromad,contrat cdi,aucun lieu,groupe sipromad6 electronicien167760,0001-01-01,13/05/2025
1,https://www.portaljob-madagascar.com/emploi/vi...,ENG-C-CPP,c/c++ software engineer,"rejoignez astek madagascar, du groupe astek, p...",Participez à des projets de transformation dig...,- formation bac+3 a bac+5 en informatique\n- m...,Informatique / web,astek madagascar,contrat cdd,aucun lieu,astek madagascar c,0001-01-01,28/09/2024
2,https://www.portaljob-madagascar.com/emploi/vi...,NaN,manager developpement rh,multisectorielle,Rattaché à la Directrice des Ressources Humain...,"• bac +4/5 en gestion, grh, sociologie, droit,...",Management / RH,inviso group,contrat cdi,antananarivo,fly technologies sarl,0001-01-01,14/02/2025
3,https://www.portaljob-madagascar.com/emploi/vi...,VE,charge commercial,"integrer boost, l'entite de distribution du gr...",Poste basé à Tanjombato\n\nLe Chargé de veille...,"titulaire d'un bac+ 4/5 en economie,marketing,...",Marketing / Communication,boost>,contrat cdi,antananarivo,jb49 charge de,0001-01-01,17/02/2025
4,https://www.portaljob-madagascar.com/emploi/vi...,NaN,projeteur coffrage & ferraillage,copilotas madagascar est la solution unique d'...,Nous recrutons un Projeteur Génie-civil & Béto...,"le candidat ideal possede un bac+2 minimum, un...",Ingénierie / industrie / BTP,copilotas madagascar,contrat cdi,antananarivo,copilotas madagascar sarl,0001-01-01,05/12/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5930,https://www.portaljob-madagascar.com/emploi/vi...,blp,boulanger patissier,boulangerie patisserie,"boulanger pâtissier\npain pizza gâteaux , cook...","avec experience , motivee et professionnel",Restauration / hôtellerie,demeo,contrat cdi,aucun lieu,immobilier consultant boulanger,0001-01-01,11/02/2025
5931,https://www.portaljob-madagascar.com/emploi/vi...,SinoRSR,responsable securite routiere-sinorsr,btp,Responsable Sécurité Routière\nLieu de Travail...,"formation bac+3 a bac+5 en securite, preventio...",Securité,sinohydro,contrat cdd,aucun lieu,sinohydro madagscar responsable,2025-08-31,03/07/2025
5932,https://www.portaljob-madagascar.com/emploi/vi...,RESPCS-0125,responsable conformite systeme,agro alimentaire,1) Comprendre le fonctionnement de l’organisat...,- titulaire d'un master 2 en gestion ou d'un d...,Qualité / Normes,societe anonyme,contrat cdi,antananarivo,anonyme247 responsable conformite,0001-01-01,07/01/2025
5933,https://www.portaljob-madagascar.com/emploi/vi...,NaN,chef de projet digital de depot,le groupe talys est un groupe familial ancre d...,- Garantir la bonne coordination et gestion du...,- titulaire d'un master en logistique ou equiv...,Logistique / Achats,talys,contrat cdi,antananarivo,talys21 chef de,0001-01-01,25/11/2024
5934,https://www.portaljob-madagascar.com/emploi/vi...,NaN,designer experimente,prestation,Contexte du projet\n\nApplication mobile de co...,competences requises\n\n1. experience en desig...,Informatique / web,entreprise,contrat cdd,antananarivo,presta good designer,0001-01-01,22/10/2024

### Export data into csv

In [6]:
df.to_csv('datasets/job_offer_no_duplicate.csv')